[workspace]
resolver = "3"
members = [
    "crates/dscan-core",
    "crates/dscan-cli",
    "crates/dscan-jni",
]
default-members = [
    "crates/dscan-core",
    "crates/dscan-cli",
]

[workspace.package]
version = "0.8.1"
edition = "2024"
authors = ["AhooraZen <ahoora935137@gmail.com>"]
license = "MIT OR Apache-2.0"
repository = "https://github.com/AhooraZen/dscan"
homepage = "https://github.com/AhooraZen/dscan"
readme = "README.md"

[profile.release]
opt-level = 3
lto = "fat"
codegen-units = 1
panic = "abort"
strip = true

[profile.dev]
debug = 1

[profile.test]
debug = 1
